### ISSUE TITLE
详细安装步骤

### ISSUE THREAD

**Issue by Sharkkkk** [kingmo888/Spyder_Simplified_Chinese#1]
可以说的详细一点吗，要下载什么文件，安装的具体流程是怎样的。或者能制作一个bat自动安装吗，真心看不懂教程，哭死

**Comment by Sharkkkk** [comment]
总算成功，发个经验帖帮助一下别人吧。首先下载spyder.mo到桌面，在桌面建立py，用**管理员权限**打开spyder复制main.py的代码，点击运行

**Comment by Sharkkkk** [comment]
最后：**非常感谢作者**

**Comment by kingmo888** [comment]
我以为挺详细的呢。

**Comment by kingmo888** [comment]
在文档底部，更新了一个更详细的文字版教程
