### ISSUE TITLE
3.2.8打开偏好设置后提示“内部错误”

### ISSUE THREAD

**Issue by xlarryzhu** [kingmo888/Spyder_Simplified_Chinese#11]
其他语言无此错误
   
 widget = plugin.create_configwidget(dlg)
    configwidget.initialize()
    self.setup_page()
    "present).") % (smart, full))
TypeError: not all arguments converted during string formatting

**Comment by kingmo888** [comment]
确实更新后有此问题，相同的一句注释，官方文件写了2遍，我去掉了导致无法匹配。已经在官方提交issues。
中文包已经同步更新修复。
