### ISSUE TITLE
python2.7 安装出错

### ISSUE THREAD

**Issue by wowarlocks** [kingmo888/Spyder_Simplified_Chinese#3]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    newf = open(newpath, 'w', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by kingmo888** [comment]
呃，我是基于py3写的，还没有测试过py2.
不过改一下基本的函数参数即可。py2中没有encoding

**Comment by wowarlocks** [comment]
![示例图片](https://github.com/kingmo888/Spyder_Simplified_Chinese/blob/master/img/2017-04-07-13-59-16.png)
我看你的示例图片是2.7的，我还以为是我的python有问题。。。

**Comment by kingmo888** [comment]
我都是基于anaconda下的3.4和2.7来的，二者都无问题。
其他的py环境倒是不太清楚。

**Comment by kingmo888** [comment]
请下载最新版本。已经修复问题。
