### ISSUE TITLE
Win 系统下安装失败：找不到 base.py

### ISSUE THREAD

**Issue by CodingOctocat** [kingmo888/Spyder_Simplified_Chinese#5]
```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    with open(configpath, 'r',encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\Anaconda3\\\\spyder\\\\config\\\\base.py'
```

**Comment by CodingOctocat** [comment]
搞了小半下午，结合 #2 终于搞好了。
对于 _Win_ 系统的解决方法是（如果缺少 `config` 等文件夹则自行创建即可）：

1. 复制 `C:\Users\xxx\Anaconda3\Lib\site-packages\spyder\config` 中的 **_base.py_**
到 `C:\Users\xxx\AppData\Roaming\Python\Python36\site-packages\spyder\config`

2. 再次执行 `python main.py` 命令（此时因为有了 **_base.py_** 文件，所以命令执行正常，但实际上并没成功😭，别急看，接着往下看👀）

3. 将 `C:\Users\xxx\AppData\Roaming\Python\Python36\site-packages\spyder\config` 中的 **_base.py（此时的 base.py 是步骤2中执行命令新生成的）_**
复制回 `C:\Users\xxx\Anaconda3\Lib\site-packages\spyder\config`

4. 将 `C:\Users\xxx\AppData\Roaming\Python\Python36\site-packages\spyder\locale` 中的 `zh-CN` 文件夹
复制到 `C:\Users\xxx\Anaconda3\Lib\site-packages\spyder\locale`


综上，表面上看其实就是要两个地方的 `config` 和 `locale` 都存在一样的内容（`base.py` 和 `zh-CN`）。

**Comment by xiaoma2016** [comment]
在window7 X64  默认路径安装Anaconda3时，报上面的错误
上面的方法中的路径在如果找不到可以参考，把XXXXXX改为系统用户名

1.1
C:\ProgramData\Anaconda3\Lib\site-packages\spyder\config

1.2
C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\spyder\config


3.1 =  1.2
C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\spyder\config

3.2 = 1.1
C:\ProgramData\Anaconda3\Lib\site-packages\spyder\config

4.1
C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\spyder\locale

4.2
C:\ProgramData\Anaconda3\Lib\site-packages\spyder\locale
