### ISSUE TITLE
打开后不是中文界面

### ISSUE THREAD

**Issue by zxh95320** [kingmo888/Spyder_Simplified_Chinese#8]
显示安装成功，语言也切换成了简体中文，可是不知道为什么依旧是英文界面。

**Comment by kingmo888** [comment]
然而并没有更多信息提供给我哦。
很难判断

**Comment by zxh95320** [comment]
![p1](https://user-images.githubusercontent.com/32194181/37602205-db509800-2bc6-11e8-923e-ff658782c5b5.png)
win10 64位

**Comment by kingmo888** [comment]
检查一下语言包目录里有没有对应的zh开头，mo结尾的语言文件
