### ISSUE TITLE
请提供po文件

### ISSUE THREAD

**Issue by pythonwood** [kingmo888/Spyder_Simplified_Chinese#9]
作者你好，建议你合并到https://github.com/pythonwood/spyder  的 spyder_profiler/locale/ 目录下
或者我来帮你，请提供po文件。

**Comment by kingmo888** [comment]
如本项目首页说明，我早就合并到官方了。你这是fork的。里面已经带着po文件。文件结构也没看、说明也没看，上来就提要求。虽然我早就公布了，但就是不给你。
